### ISSUE TITLE
Easy deploy to Heroku

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#107]
It should be drop-dead simple to deploy an instance of Origin demo-dapp to Heroku. 

Heroku-Github integration instructions here: https://devcenter.heroku.com/articles/github-integration

The thorny part of this feature is that it requires that the published [npm version of origin.js](https://www.npmjs.com/package/@originprotocol/origin) be working and compatible with the version of demo-dapp. (Heroku will install that npm package like any other.)

EDIT: Of course, we could also have our `package.json` refer to a specific _commit_ instead of a version. This seems a brittle, but perhaps is okay given our early state of development. 

Related: https://github.com/OriginProtocol/demo-dapp/issues/105 
Where there is discussion about how to do versioning.

**Comment by joshfraser** [comment]
Have the Heroku buttons working on the company-website repo already:

https://github.com/OriginProtocol/company-website

Wish there was a nicer way to detect which brach you are currently on in the Github UI versus showing separate buttons for `develop` and `master`. Sounds like a lot of people want that functionality, but Github don't seem in a rush to implement it:

https://github.com/github/markup/issues/913

**Comment by wanderingstan** [comment]
Awesome! Such a cool feature. 

I proposed a few edits to the readme after trying out the deploy:
https://github.com/OriginProtocol/company-website/pull/165

**Comment by micahalcorn** [comment]
Done via #241 ✅
