### ISSUE TITLE
form-data missing in package.json

### ISSUE THREAD

**Issue by inkredabull** [OriginProtocol/demo-dapp#132]
Against the latest `develop`, when trying to run via `npm run start`, I get:
```
ERROR in ./node_modules/origin/dist/index.js
Module not found: Error: Can't resolve 'form-data' in '/repos/OriginProtocol/demo-dapp/node_modules/origin/dist'
 @ ./node_modules/origin/dist/index.js 894:17-37
 @ ./src/services/origin.js
```
(PR forthcoming)

**Comment by inkredabull** [comment]
https://github.com/OriginProtocol/demo-dapp/pull/133

**Comment by micahalcorn** [comment]
@inkredabull Is this just a matter of the current `develop` branch not playing well with the currently-published npm package? I think that lib is [required by origin-js](https://github.com/OriginProtocol/origin-js/blob/develop/src/ipfs-service.js#L7) only and maybe should not be installed in this app.

**Comment by micahalcorn** [comment]
@inkredabull it does look like the package might be missing from origin-js's `'package.json`. I guess it's possible that we all already have it in our `package-lock`s, so we're not seeing the error?

**Comment by DanielVF** [comment]
These instructions work for me, with no errors.

    #Terminal A
    mkdir -p origin
    cd origin
    git clone https://github.com/OriginProtocol/origin-js.git
    cd origin-js
    git checkout develop
    npm install
    npm link
    npm start

    #Terminal B (start in the origin directory you just made)
    git clone https://github.com/OriginProtocol/demo-dapp.git
    cd demo-dapp
    git checkout develop
    npm install
    npm link origin
    npm run start

    #Then with a metamask enabled browser, go to http://localhost:3000

**Comment by DanielVF** [comment]
It's possible thought that my computer is special case, and this working only here.

**Comment by dobbs** [comment]
I had the same symptoms yesterday.  I can confirm that the work-around @DanielVF described also works for me.

**Comment by dobbs** [comment]
@inkredabull, in case this helps you with the PR:

My original installation of `demo-dapp` does point to the correct version of `origin-js`:

1. Revision in `develop` I have checked out:
```
git show --oneline
66f139e (HEAD -> develop, origin/develop) Merge pull request #131 from OriginProtocol/upgrade-modules
```

2. Has the dependency on `origin-js` declared like this:
```
grep origin-js package.json
    "origin": "OriginProtocol/origin-js#develop",
```

3. The installed version reports being from SHA `44390dd`:
```
grep _resolved node_modules/origin/package.json
  "_resolved": "github:OriginProtocol/origin-js#44390dda628d0670bd52d6f0d30f4cfc818aaad4",
```

4. The version of `origin-js` I have checked out from the earlier test matches `44390dd`:
```
cd ../missing-form-data/origin-js/
git show --oneline
44390dd (HEAD -> develop, origin/develop) Merge pull request #138 from OriginProtocol/20180430/use_our_own_web3
```

Something in the way npm installs from github is different from what happens with the `npm link`.

**Comment by inkredabull** [comment]
Thanks @micahalcorn @DanielVF @dobbs. I noticed that after pulling `develop` for this repo and running `npm install` that package.json and package-lock.json are updated; I would expect them to not need to be.  I'll run the suggestion from @DanielVF to see if that clears things up.

**Comment by inkredabull** [comment]
Suggestion from @DanielVF works for build/running; no getting form-data issue. Will close this Issue/PR. 

@DanielVF should the [dev instructions](https://github.com/OriginProtocol/demo-dapp#developing-with-a-local-chain) be updated with your suggestion as the canonical way?

**Comment by inkredabull** [comment]
Just noticed that `package.json` and `package-lock.json` are modified after I run the commands in [Terminal B](https://github.com/OriginProtocol/demo-dapp/issues/132#issuecomment-385584556)

**Comment by inkredabull** [comment]
Verifying that after I run `npm link origin` in Terminal B I get updates in the package files:

```
➜  demo-dapp git:(develop) ✗ git status
...
	modified:   package-lock.json
	modified:   package.json
```

Upgraded npm. FWIW:
```
➜  bluxomelabs > cd ~/repos/origin
➜  origin node -v
v8.7.0
➜  origin npm -v
6.0.0
```

**Comment by inkredabull** [comment]
I guess that (mods in pkg files) is expected behavior; just makes it less intuitive to develop around.

**Comment by inkredabull** [comment]
Seeing LISTING_FETCH_IDS_SUCCESS in the console; realizing that empty listings have to do with Redux parsing. Investigating.
