### ISSUE TITLE
Handle non-matching routes

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/demo-dapp#139]
We currently render nothing on URL that fails to match a route (like a conventional 404). Add a friendly UI to improve this experience, similar to https://www.originprotocol.com/missing.

**Comment by lastmjs** [comment]
By the way, I'm taking this on

**Comment by lastmjs** [comment]
The current solution in the pull request will only catch single page app routes, after the #. In my opinion, we definitely should not even be doing routing like that with the #. But for now, a 404 page will only be displayed for those routes. Do you want me to fix the problem for routes that go through to the server?

**Comment by micahalcorn** [comment]
@nick HashRouter question ☝️

**Comment by nick** [comment]
We'd like the demo-dapp to be deployable in subdirectories and directly on IPFS ([example](https://gateway.originprotocol.com/ipfs/Qman5QYeKEZ1y7iTdWFfnUkpEbnmJSnGPThPLRFj9yMMPU/#/)) so I think we should stick with HashRouter by default, but possibly make it optional later on. So I think your existing solution is good for now :-)

**Comment by micahalcorn** [comment]
@lastmjs see https://github.com/OriginProtocol/company-website/blob/master/templates/404.html for assets and probably some pretty rough CSS. 😬

**Comment by lastmjs** [comment]
Now being tracked here: https://github.com/OriginProtocol/demo-dapp/pull/165

**Comment by lastmjs** [comment]
@micahalcorn Do you want it to look identical to https://www.originprotocol.com/missing?

**Comment by micahalcorn** [comment]
@lastmjs that was what the designer suggested. I don't know that it's necessarily a priority.

**Comment by lastmjs** [comment]
Perhaps we should close this issue and reopen another one to spruce up the design?

**Comment by micahalcorn** [comment]
Done via #165 ✅
