### ISSUE TITLE
Link to etherscan for transaction, accounting for network

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#18]
On blockchain transactions, e.g. posting listing here:
https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/demo-step-4.js#L12
 
Determine if we are on mainnet, testnet, or local
https://ethereum.stackexchange.com/a/23905/20332

And then link to page transaction `tx` on network's etherscan, e.g. 
https://rinkeby.etherscan.io/tx/0xfa2108102935c48eac0869c901ea36588704110eac6fdb79f958841d1821fc28

Of course not possible for local testrpc network.

**Comment by smazurov** [comment]
probably best after #7

**Comment by wanderingstan** [comment]
@phyninja you interested? :)

**Comment by micahalcorn** [comment]
Done via #226 ✅

**Comment by micahalcorn** [comment]
This has been removed via https://github.com/OriginProtocol/demo-dapp/commit/0c64f5015deb12e6be971d7db6320edc317715f3. When the link is visited for an unsold listing, there is no information, which causes confusion. We now have etherscan links for the transactions in the purchase detail.
