### ISSUE TITLE
Dockerize this thing

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/demo-dapp#19]
Would be great to add a Dockerfile to make it easier for people using Docker to get up and running with the demo app.

**Comment by wanderingstan** [comment]
After talking @moe456 on slack, I'm not sure this is as much of an issue. At the time, running the DApp meant running an IPFS daemon, testrpc, and truffle. That was a lot to install. 

Now we have our own IPFS gateway, and truffle develop replaces testrpc. So it's just truffle, which isn't so bad. I think we can close this.

@joshfraser What do you think?
