### ISSUE TITLE
Add way for admins to get ListingId of a listing

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#221]
This one's for you @andrewhyde 

Hide it in html, img `title`, wherever...

**Comment by tyleryasaka** [comment]
An alternative is to allow hiding listings by address: https://github.com/OriginProtocol/demo-dapp/pull/222

**Comment by micahalcorn** [comment]
@tyleryasaka will this now be closed?

**Comment by wanderingstan** [comment]
@tyleryasaka looking at the code, I'm now realizing theres stuff in there that we would want to later rip out once the hidelist filtering is done by the Indexing Server. E.g. adding the `shouldRender` property. 

@micahalcorn if we can figure out a one-line solution to reveal the listingId to the admins, I'd rather go with that for now. (And use the existing hidelist code that's already there.)

**Comment by wanderingstan** [comment]
I put it in `data-listing-id` param on listing title on grid page.
