### ISSUE TITLE
Add language selection dropdown menu

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/demo-dapp#246]
Sub-task of: https://github.com/OriginProtocol/demo-dapp/pull/238

As a user, I want to change the language of the DApp using a dropdown menu that shows all available languages. 

According to Aure, there is no design for this menu 

Let's put it in the footer and make it match other footer link styling as much as possible. 

This task will require moving language config currently found in `index.js` to Redux

**Comment by micahalcorn** [comment]
Let's actually put this in the footer, especially if we are auto-detecting the preferred language in most cases. cc @wanderingstan

**Comment by jordajm** [comment]
Good call @micahalcorn - description udpated.

**Comment by micahalcorn** [comment]
Done via #260 ✅
