### ISSUE TITLE
Replace sentence concatenation with full sentences that can be translated

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/demo-dapp#247]
Sub-task of: https://github.com/OriginProtocol/demo-dapp/issues/63

There is currently sentence concatenation logic in `notifications.js` and possibly other components that is not easily translated into other languages. 

This logic should be replaced with full strings that can be translated.

**Comment by micahalcorn** [comment]
I believe that this is no longer applicable thanks to https://github.com/OriginProtocol/demo-dapp/pull/261/commits/ae39bc46848a6fc4eb40d14d7e603514dab3b218.
