### ISSUE TITLE
Research and implement a way to localize react-jsonschema-form

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/demo-dapp#255]
`react-jsonschema-form` is used in `listing-create.js` to allow users to create listings. 

We need to figure out a way to display form labels, selection options, etc in any supported language.

**Comment by micahalcorn** [comment]
@jordajm potentially related, I noticed that we're not translating the categories on the listing cards.

**Comment by jordajm** [comment]
Noted - thanks @micahalcorn

**Comment by jordajm** [comment]
Will be completed by https://github.com/OriginProtocol/demo-dapp/issues/258
