### ISSUE TITLE
Localization for schemas

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/demo-dapp#258]
Schemas currently have English strings for enums and labels, and that makes it hard to localize those strings in the places where the schemas are used in the DApp. 

In https://github.com/OriginProtocol/demo-dapp/issues/256, it was decided that the solution would involve replacing English strings in schemas with IDs similar to the other `react-intl` IDs in the DApp, and then creating a set of files that mirrors the schemas which would contain mappings of schema IDs and `defaultMessage` strings so they can be easily extracted for translation. 

The new directory structure will be something like this:
**schemas**
&nbsp;&nbsp;&nbsp;&nbsp;|_ announcements.json
&nbsp;&nbsp;&nbsp;&nbsp;|_ for-sale.json
&nbsp;&nbsp;&nbsp;&nbsp;|_ housing.json
&nbsp;&nbsp;&nbsp;&nbsp;|_ **schemaMessages**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|_ announcements.js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|_ for-sale.js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|_ housing.js

We will also need a couple of new util functions to help with the localization of these extracted messages, as well as a globally available instance of `react-intl` so that its functions can be used outside of react components.

**Comment by jordajm** [comment]
It turns out that this can't be structured as I defined in the description because I was planning to use the `defineMessages` method of `react-intl`, but that method is run by babel in the compiling phase, not as part of the react app, so the messages object has to be defined in the react code that is compiled by babel, not in the `/public/schemas/schemaMessages` location that I originally proposed. 

I'll have to add the `defineMessages` call for schema strings to `/src/schemaMessages` so that babel can define the messages during compilation.

**Comment by micahalcorn** [comment]
Done via #262 ✅
