### ISSUE TITLE
Do correct swapping of web3 in global context

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#29]
`react-web3` package is slick, but doesn't do the reccomended swapping in of local version of web3, as described here:
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#partly_sunny-web3---ethereum-browser-environment-check

We're already using my patched version of react-web3. I'm in contact with the developer of it, though he is slow to respond.

**Comment by wanderingstan** [comment]
@micahalcorn Did you fix this in when you exorcized `react-web3`? 
Or maybe @tyleryasaka , in your update to how we do web3 in platform?

**Comment by micahalcorn** [comment]
@wanderingstan no, I believe that @aiham was working on this.

**Comment by micahalcorn** [comment]
I believe this will happen as a byproduct of @nick's identity integration this week.

**Comment by micahalcorn** [comment]
Done via https://github.com/OriginProtocol/demo-dapp/commit/546e2d2396f92a14555921ac09bc75a03f526916 ✅
