### ISSUE TITLE
Show creator address of listing

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#31]
On listing-detail, show the eth address that created the listing.

**Comment by bretfunk** [comment]
Does this look ok?

Created on <date>
by <address>

<img width="474" alt="screen shot 2018-02-02 at 4 37 52 pm" src="https://user-images.githubusercontent.com/2019012/35755987-7bb064fa-0837-11e8-994c-618884cc075c.png">

**Comment by wanderingstan** [comment]
Looks great! I'm sure Aure will make some styling changes, but that's easy once the data is in there.

**Comment by wanderingstan** [comment]
I'm going to close this, as I think it may already be there, and will be covered when we fully do identity in any case.
