### ISSUE TITLE
Get id of newly created listing

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#33]
This is surprisingly hard, as web3 doesn't give any info returned from a contract method. 

We'll probably need to modify our code that waits for transaction to finish, and then fetch the listing id (index) from there.

**Comment by bretfunk** [comment]
When a create method is called in the contract, it returns the ```listing.length``` and calls the ```NewListing``` event.  Couldn't you use one of those to determine the id of a newly created listing?  Here is the code in the contract: 
```
NewListing(listings.length-1);   <-- event that returns the created id (id's start at 0)
return listings.length;    <-- returns the total listings length, subtract 1 for the id
```
Thoughts?

**Comment by wanderingstan** [comment]
A contract method that modifies state (non-constant) can't return a value. Even if there's a `return()` statement--confusing!

An event is good, but what happens when 10 listings were created in one block. How do you you know which event corresponds with the listing that you just created? 

I'm not sure what the right way to solve this is, other than to monitor the events and look for the one that has you as the listing creator. Or better yet (in case you're submitting multiple listings at once), has the IPFS hash of this particular listing.

**Comment by wanderingstan** [comment]
Having thought on this more, I'm more leaning toward including the ipfs hash in the event. That's the most solid connection between the client creating the listing and when ends up on the chain. 

Like this:

    NewListing(listings.length-1, _ipfsHash);

Thoughts?

**Comment by bretfunk** [comment]
Roger. Agreed. Is the client doing anything with the id or are we just updating the contract?

________________________________

**Comment by wanderingstan** [comment]
More of a UI/UX issue I think. After creating a new listing, the first thing you're going to want to do is look at it. Right now the client can't be sure of the id of the new listing, so we just "take the easy way out" and return you to the page of *all* listings. :)

(I suppose this opens up anther possibility, of scanning the new listings and picking the newest one created by the user, but that feels brittle. Down the road their could be automated system creating dozens of listings at a time, and would want to update some internal db with the id of the created origin listing.)

**Comment by bretfunk** [comment]
I have added the ipfs hash to the NewListing event on the topic/contract-dev branch.  I tried to create a test for it but discovered that you can't write tests for events yet?!  If this is incorrect please let me know.

**Comment by wanderingstan** [comment]
Given that we totally changed how Listings are referenced (now they exist as own contract) I'm closing this one out,.
