### ISSUE TITLE
upgrade marked library in package-lock.json

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/demo-dapp#51]
potential security vulnerability

**Comment by wanderingstan** [comment]
In df85e05f3ae034a23c8eab220a7b94316e1429b0
updated `package.json` to require at [least latest version which is 0.3.9](https://www.npmjs.com/package/marked)

`npm install` auto-generated new `package-lock.json` with correct version too.  

Demo server confirmed to now be running new version.

@joshfraser Was there a mention of a vulnerability somewhere?

**Comment by joshfraser** [comment]
yeah github was showing a big old warning at the top of the repo
