### ISSUE TITLE
Strange behavior for date/time picker in jsonschema form

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#53]
Lots of weird stuff. Changing hour can change the day. Different value than typed appears.

**Comment by wanderingstan** [comment]
The date picker works fine on their demo form: 
https://mozilla-services.github.io/react-jsonschema-form/

Might be some collision of css class or id names, or javascript globals.

**Comment by garrisons** [comment]
One of the things that I'm seeing is that If I set the hour to 12 and change it from PM to AM the hour changes to 6. That kind of weirdness makes me think not css or ids?

**Comment by wanderingstan** [comment]
Yeah it's really weird. I don't get what's different between our page and the demo page that would induce such erratic behavior. 

In the worst case we need to do a regression test from our code to theirs to see what breaks it.

**Comment by nikkwong** [comment]
@wanderingstan  https://github.com/mozilla-services/react-jsonschema-form/issues/622

Looks like this issue was fixed with commit ```6152e34``` as part of their ```v1.0``` release. Upgrading the lib should suffice.

**Comment by wanderingstan** [comment]
That's great news, thanks @nikkwong ! 

@ryana -- see any issues with doing a `npm update` on our demo machine?

**Comment by wanderingstan** [comment]
Confirmed fix locally. 
In commit 05fc8c0333285f908c00bc2c1aa98a754c26b6e2
