### ISSUE TITLE
Block HTTP on the IPFS gateway

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/demo-dapp#57]
We should only use HTTPS for the IPFS gateway. This prevents eavesdropping which listings are being viewed, and prevents data from being modified in transit before it hits the user.

We should prevent us from accidentally using HTTP in the future, as well as help other people building DAPs. I think the best way to do this is to not allow the gateway to be used over HTTP at all. It should be HTTPS only.

**Comment by DanielVF** [comment]
@ryana

**Comment by ryana** [comment]
Hey @DanielVF `http` requests are already being redirected to `https` on `gateway.op.com`. Did you see it not behaving that way anywhere? If so can you let me know where? Otherwise, looks like we're good and we'll close this one.

**Comment by DanielVF** [comment]
That still leaves it open to seeing what URL is being requested, and the possibility of inserting your own content. (Since the attacker could see the initial clear text connection.)

We need to make sure that nobody uses HTTP ever on this infrastructure, and it seems like just making it so it never seems to work would be the best way.

**Comment by ryana** [comment]
Done. Returning a 505 and an `X-Error-Message: This server only supports HTTPS` in response to any request on port 80.
