### ISSUE TITLE
Only allow data images for listings

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/demo-dapp#58]
We should to force photos be embedded data urls.

Currently, you could just include an http or https image url in the pictures json, and it would be used instead of a data url. This would allow someone to track when their image is viewed, or who is viewing it, or change the image during or after the sale, with no way of knowing about this during a later dispute.

This is probably best done as part of a validation/migration step when loading listing data.

**Comment by DanielVF** [comment]
This should probably be done as a part of https://github.com/OriginProtocol/demo-dapp/issues/59

**Comment by joshfraser** [comment]
Ideally, you would be able to link to remote images as long as they are hosted on IPFS.

**Comment by wanderingstan** [comment]
For now, did a quick fix to the dapp to only allow data protocol urls:
https://github.com/OriginProtocol/demo-dapp/commit/ef00de82c90b7971d8ef06d4dacd67ff4a08846a
Its just a quick check at render time. 

@joshfraser I suspect the "right" solution will be to not have only ipfs hashes in the schema for photos -- no urls or data.

**Comment by wanderingstan** [comment]
Gonna call this one closed, as #59 is the real deal.
