### ISSUE TITLE
Branched react-web3 package installation fails silently

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/demo-dapp#60]
In step 10 of the local DApp installation, there are no obvious errors during `npm install`. However, upon `npm run start`, I get the following error:

```
Failed to compile.

Error in ./src/components/app.js
Module not found: 'react-web3' in /.../Solidity/origin-demo-dapp/src/components

 @ ./src/components/app.js 20:16-37
```

Sure enough, the `node_modules/react-web3` folder only contains `README.md` and `package.json`. It is missing the `dist` folder and the package code. If I remove the installed branch of the package and edit the `package.json` dependency to `"react-web3": "0.4.3"`, then the app boots up fine. I have tried a variety of removals and reinstalls to no avail. Let me know what else I can tell you.

**Comment by tyleryasaka** [comment]
I am also experiencing this issue.

**Comment by tyleryasaka** [comment]
Ok, this appears to be a node version issue.

Doesn't seem to compile on `v6.11.1` or `v7.0.0`, but does work on `v8.5.0`.

Using nvm, this should get it working:

```
$ nvm install v8.5.0 && nvm use v8.5.0
```

Should probably document this somewhere. I think we can also specify the version in the `engines` field, both in this repo and in the react-web3 repo. I'll look into that.

**Comment by wanderingstan** [comment]
Good catch @tyleryasaka , I've updated the readme.
https://github.com/OriginProtocol/demo-dapp/commit/8d5fde6819eb4569419ed151cc9ae6ce332c0379

The `engines` field seems to not really be enforced anywhere.

**Comment by tyleryasaka** [comment]
@wanderingstan Great! Yeah I noticed the same issue with the engines field. Doesn't seem very useful.

**Comment by wanderingstan** [comment]
@tyleryasaka @micahalcorn  Are we in agreement that this is a node version issue, and I can close this issue?

**Comment by tyleryasaka** [comment]
@wanderingstan Yes I feel confident that's what it is. I think if @micahalcorn can confirm that this fixes the issue for him then this is good to close.

**Comment by micahalcorn** [comment]
@wanderingstan Confirmed on `8.5.0` and `8.9.4`. Thanks @tyleryasaka!
