### ISSUE TITLE
Add explicit license

### ISSUE THREAD

**Issue by Kentoseth** [OriginProtocol/demo-dapp#69]
We don't have an explicit license for this repo.

Good idea to add one.

**Comment by ldub** [comment]
+1 Could you please add a license?

**Comment by wanderingstan** [comment]
@joshfraser I assume we're going MIT on this as well?

**Comment by joshfraser** [comment]
Yep

**Comment by wanderingstan** [comment]
Done in https://github.com/OriginProtocol/demo-dapp/commit/8c47a6f5247523d917e45cad4e964f4ff61d7c45
