### ISSUE TITLE
Update web3 to latest version

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#7]
Currently using version 0.18.4 when latest is >1.0. 

Noticed when interacting with `utils`:
https://web3js.readthedocs.io/en/1.0/web3-utils.html

**Comment by wanderingstan** [comment]
Related: https://github.com/OriginProtocol/demo-dapp/issues/29

**Comment by wanderingstan** [comment]
Related: https://github.com/OriginProtocol/demo-dapp/issues/29

**Comment by micahalcorn** [comment]
I believe this will happen as a byproduct of @nick's identity integration this week.

**Comment by nick** [comment]
Done in #140
