### ISSUE TITLE
Fallback for folks without a web3-enabled browser

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/demo-dapp#73]
This could be as simple as instructions how to complete the transaction using MyEtherWallet.com. 

Or a slick integration for popular hardware wallets like the ledger.

**Comment by wanderingstan** [comment]
@Nick has his Dapp working without metamask using the new Web3:
https://originprotocol.slack.com/archives/C7XHKV6TG/p1517172702000099

Seems like a great way to do it.

**Comment by joshfraser** [comment]
Oh that's awesome. Hadn't seen that!

**Comment by dagumak** [comment]
@wanderingstan Link seems broken, do you still have the website? I would love to see how it works.

**Comment by kyriediculous** [comment]
@dagumak  https://github.com/OriginProtocol/identity-playground

**Comment by micahalcorn** [comment]
No longer necessary due to https://github.com/OriginProtocol/demo-dapp/commit/cad14ffdfadd5139509dff9d29018958a57d5772 and https://github.com/OriginProtocol/mobile-app ✅
