### ISSUE TITLE
Detect wallet(provider) in use and change name/icon 

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#84]
Detect which wallet user is using (Metamask or whatever) and change terminology in the dapp. 

So instead of saying "Complete transaction in Metamask" it should say, "Complete transaction in Trust Wallet". 

See  here for exact location of name in `web3` object: https://github.com/TrustWallet/trust-web3-provider#how-to-identify-trust-provider

cc: @vikmeup of Trust Browser

**Comment by micahalcorn** [comment]
@jordajm I think that this might be covered by #83, which is blocked. What do you think?

**Comment by jordajm** [comment]
Hmmm - I'm not sure - seems like this one is slightly different b/c it refers to changing name/icon throughout the app, but since @ambertch is working on #83, it probably makes sense for him to grab this one too..?

**Comment by micahalcorn** [comment]
@jordajm ah, I see the difference. Go ahead and take this one if you want.

**Comment by wanderingstan** [comment]
This SO question seems to have some good code on detecting what provider is being used: https://ethereum.stackexchange.com/questions/24266/elegant-way-to-detect-current-provider-int-web3-js

**Comment by jordajm** [comment]
PR submitted here: https://github.com/OriginProtocol/demo-dapp/pull/178

The title of this issue references icons that need to be changed, but I wasn't able to locate any icons. I did a "find all" on the phrase "MetaMask" and replaced those hard-coded strings with dynamic provider names. 

Let me know if I missed anything. 

Also, this may be blocked by the pending updated way to reference `web3` in demo-dapp as noted here: https://github.com/OriginProtocol/demo-dapp/issues/126

**Comment by micahalcorn** [comment]
Done via #178 ✅
