### ISSUE TITLE
Create Listing error: Uncaught Error: no schema with key or ref

### ISSUE THREAD

**Issue by bobio7** [OriginProtocol/demo-dapp#93]
When I select any category and create listing. Chrome console returns below error::
`Uncaught Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"
    at Ajv.validate (ajv.js:95)
    at Ajv.validateSchema (ajv.js:183)
    at Ajv._addSchema (ajv.js:317)
    at Ajv.validate (ajv.js:97)
    at validateFormData (validate.js:196)
    at Form.validate (Form.js:166)
    at Form.js:87
    at Form._this.onSubmit (Form.js:103)
    at HTMLUnknownElement.boundFunc (ReactErrorUtils.js:63)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:69)`

The current json-schema is draft-07. I have tried update it in public->schemas, but still have the same 'no schema with key or ref' error

**Comment by tyleryasaka** [comment]
@bobio7 I am not able to reproduce this issue. Would you mind sharing your node version? And I assume no changes have been made to your local `package-lock.json`?

**Comment by nsimon** [comment]
Hey @bobio7, @tyleryasaka I think I fixed this. See my PR: https://github.com/OriginProtocol/demo-dapp/pull/88

**Comment by tyleryasaka** [comment]
Yep! I was going down that same route. Beat me to it!

**Comment by nsimon** [comment]
Well... my first change, to update **draft-04** to **draft-06** really helped. It resulted in a more informative error message that led me to the fix.

**Comment by wanderingstan** [comment]
Thank you @nsimon for reminding me this is fixed!
