### ISSUE TITLE
Switch to standard alertify npm module

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#98]
@micahalcorn had to patch the old alertify to work with our webpack, which necessitated us creating our own fork of the library. See commit https://github.com/OriginProtocol/demo-dapp/commit/b3dd1babcac01e1c6f7ecca039bb0fd40b510dba

I'd vote that we just pick one of the standard supported npm packages and run with it rather than have the messiness of maintaining our own fork. 

@ryana @joshfraser any opinions on this? 

(Micah's patch: https://github.com/micahalcorn/alertify.js/commit/fe25d03893b0a10697127df2b1d90718be47089e )

**Comment by micahalcorn** [comment]
I would agree. It's worth noting that there was at least some desire for uniformity between the DApp and company website (see #46). I'm happy to update both to a newer version and/or tweak the styles in an effort to offer the same UX, if necessary.

**Comment by joshfraser** [comment]
We should have a longer conversation around dependencies on the engineering call tomorrow, but we should try and keep this app really simple with as few third-party dependencies as possible. 

It feels a bit silly to have to maintain a whole separate package around this when we can replicate this functionality ourselves with a few lines of CSS and JS. It feels like we're probably making this way too complicated.

**Comment by wanderingstan** [comment]
@micahalcorn What did we end up implementing on this, and can I close this one out? :)

**Comment by micahalcorn** [comment]
@wanderingstan nothing yet. I have a partially-baked replacement, but I've had it on the back burner while focusing on the UI. And it would really be best to have Matt & Aure settle on the alert/message/notification UX distinction before merging a solution to this issue.

**Comment by micahalcorn** [comment]
Done via #145 ✅
